### PR TITLE
Enable the Realtime API 

### PR DESCRIPTION
**Pull request by lukepolo**
Its nice to have real time usage !

$active_users = \LaravelAnalytics::getActiveUsers();

https://developers.google.com/analytics/devguides/reporting/realtime/v3

### CODE REVIEW

**Comment by freekmurze** [comment]
Awesome, thanks, I'll take a look at it soon! One problem I can already foresee: these realtime queries shouldn't be cached. Or at least not as long as the other queries.

**Comment by freekmurze** [comment]
Ignore my comment on the caching: after taking a closer look I see that you already took care of it. Nice!

**Comment by lukepolo** [comment]
Also I should mention to use it you must register for the "beta', (I had access less than 5 mins)

https://docs.google.com/forms/d/1qfRFysCikpgCMGqgF3yXdUyQW4xAlLyjKuOoOEFN2Uw/viewform

**Comment by juukie** [comment]
Cool feature!
Can you also check that all method params are in the docblocks?

**Comment by lukepolo** [comment]
Yup sorry about that, knew i was forgetting something!

**Comment by freekmurze** [comment]
If you know how to do it, could you also add some tests for these new methods?

**Comment by lukepolo** [comment]
Sure no problem, ill have them added in a few

**Comment by lukepolo** [comment]
Let me know if the coverage was ok

**Comment by freekmurze** [comment]
Very nice! Thanks!

**Comment by aftabnaveed** [comment]
I installed v3.0.1 but looks like this feature is not yet there. Am I missing something here?

**Comment by freekmurze** [comment]
The realtime API is only support in v1 of this package. It has been dropped in v2.

v1 might work for you, be please keep in mind that we don't provide any support anymore for that version.

**Comment by aftabnaveed** [comment]
I think to have figured it out, would need to put it in a right shape. 

```php
$analytics = Analytics::getAnalyticsService();
$results = $analytics->data_realtime->get(
	      'ga:4534923',
	     'rt:activeUsers');

return $results->rows[0][0];
```

**Pull request merged**
